version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: housekeeper-mongo
    ports:
      - "27017:27017"
    volumes:
      - /Users/aaron/code/docker/containers/mongo/data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=housekeeper
    restart: unless-stopped
