Port=19090
JwtSecret="your-secret-key-change-this-in-production"
JwtExpire=24

[RdbConfig.redis]
host="http://127.0.0.1"
port=6379
username=""
password=""

[RdbConfig.mongo]
host="http://127.0.0.1"
port=27017
username=""
password=""