Port=19090

[RdbConfig.redis]
host="redis"
port=6379
username="default"
password="1433223qQ"

[RdbConfig.mongo]
host="mongo"
port=27017
username=""
password=""

[Jwt]
secret_key="123456"
expire=256000

[Admin]
Username="admin"
Password="admin@123"
