services:
  redis:
    image: redis:latest
    container_name: housekeeper-redis
    ports:
      - "6379:6379"
    volumes:
      - ./containers/redis/data:/data
    command: redis-server --requirepass 1433223qQ
    restart: unless-stopped 

  mongo:
    image: mongo:latest
    container_name: housekeeper-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./containers/mongo/data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=housekeeper
    restart: unless-stopped
