Port=19090

[RdbConfig.redis]
host="127.0.0.1"
port=6379
username="default"
password="1433223qQ"

[RdbConfig.mongo]
host="127.0.0.1"
port=27017
username=""
password=""

[Jwt]
secret_key="123456"
expire=256000

[Admin]
Username="aaron"
Password="aaron519"
