Port=19090
JwtSecret="your-secret-key-change-this-in-production"
JwtExpire=24

[RdbConfig.redis]
host="redis"
port=6379
username="default"
password="1433223qQ"

[RdbConfig.mongo]
host="mongo"
port=27017
username=""
password=""

[Jwt]
secret_key="change-this-secret-key-in-production"
expire=256000

[Admin]
Username="admin"
Password="change-this-password"
